spree-snippets/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :snippets do
      collection do
        get :create_draft
      end
    end
  end
  match "/pages/:slug" => "pages#display", :as => :page
end

spree-snippets/app/models/spree/snippet.rb
class Spree::Snippet < ActiveRecord::Base
 attr_accessible :slug, :content
end

spree-snippets/app/controllers/spree/admin/snippets_controller.rb
class Spree::Admin::SnippetsController < Spree::Admin::ResourceController
  update.after :expire_cache
  create.after :expire_cache

  def create_draft
    @snippet = Spree::Snippet.create!
    redirect_to edit_admin_snippet_url(@snippet.id)
  end

  def expire_cache
    Rails.cache.delete('snippets')
  end
end

spree-snippets/app/controllers/spree/pages_controller.rb
module Spree
  class PagesController < BaseController
    def display
      @slug = "#{params[:slug]}-#{I18n.locale}"
    end
  end
end

spree-snippets/app/helpers/spree/snippet_helper.rb
module Spree::SnippetHelper

  # snippet can be something that responds to "slug" and "content",
  # or a slug, or an id
  def render_snippet(snippet)
    if snippet.respond_to?('content')
      @snippet = snippet
    elsif snippet.kind_of?(Fixnum)
      @snippet = Spree::Snippet.find(snippet)
    elsif snippet.kind_of?(String)
      @snippet = Spree::Snippet.find_by_slug(snippet)
    else
      raise "Unable to handle snippet '#{snippet}'"
    end

    if @snippet.nil?
raise "Snippet '#{snippet}' not found"
    end
    return nil unless @snippet

    template = ERB.new File.read(File.expand_path(snippet_wrapper_absolute_path))
    template.result(binding).html_safe
  end

  private

  # Returns the location of the snippet wrapper, which is dependent on how spree is installed.
  def snippet_wrapper_absolute_path
    engine_path = File.join(File.dirname(__FILE__), '..', '..', '..')

    [Rails.root, engine_path].each do |root|
      absolute_path = File.join(root, snippet_wrapper_path)
      return absolute_path if File.exists?(absolute_path)
    end
    raise "Unable to find snippet wrapper using path '#{snippet_wrapper_path}'"
  end

  # Override the location returned by this method if you want your own snippet wrapper template
  def snippet_wrapper_path
    'app/views/spree/snippets/_snippet.html.erb'
  end

end

spree-snippets/app/views/spree/admin/snippets/_form.html.erb
<%= stylesheet_link_tag 'formtastic' %>

<%= f.inputs do %>
  <% if params[:action] == "edit" %>
    <%= f.input :slug %>
  <% else %>
    <%= f.input :slug %>
  <% end %>
  <%= f.input :content, :as => :text %>
<% end %>

spree-snippets/app/views/spree/admin/snippets/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t("editing_snippet") %></h1>

<%= render "spree/shared/error_messages", :target => @snippet %>

<%= semantic_form_for(:snippet, :url => object_url, :html => { :method => :put }) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
	<p class="form-buttons">
    <%= button t("actions.update"), nil, 'submit' %>
    <%= t("or") %> <%= link_to t("actions.cancel"), collection_url %>
  </p>
<% end %>

spree-snippets/app/views/spree/admin/snippets/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<div class='toolbar'>
  <ul class='actions'>
    <li id="new_product_link">
      <%= button_link_to t("new_snippet"), create_draft_admin_snippets_url, {:icon => 'add'} %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%=t("snippets") %></h1>

<table class="index">
	<tr>
		<th><%=t("snippets_slug")%></th>
		<th><%=t("action")%></th>
  </tr>
	<tbody>
    	<% @snippets.each do |snippet| %>
		<tr class="<%= cycle('even', 'odd') %>" id="<%= dom_id snippet %>">
			<td>
				<%= snippet.slug %>
			</td>
			<td>
        <%= link_to_edit snippet %>
        <%= link_to_delete snippet %>
	    </td>
		</tr>
		<% end %>
	</tbody>
</table>

spree-snippets/app/views/spree/admin/snippets/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t("new_snippet") %></h1>

<%= render "spree/shared/error_messages", :target => @snippet %>

<%= semantic_form_for(:snippet, :url => collection_url) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
	<p class="form-buttons">
    <%= button t("actions.create"), nil, 'submit' %>
    <%= t("or") %> <%= link_to t("actions.cancel"), collection_url %>
  </p>
<% end %>

spree-snippets/app/views/spree/pages/display.html.erb
<%= render_snippet(@slug) %>

spree-snippets/app/views/spree/snippets/_snippet.html.erb
<div id="snippet_<%=@snippet.id%>"><%= @snippet.content %></div>