spree-faq/config/routes.rb
Spree::Core::Engine.routes.prepend do
  namespace :admin do 
    resources :question_categories
    resources :questions
  end
  match :faq, :to => 'faqs#index', :as => 'faq'
end

spree-faq/app/models/spree/question.rb
class Spree::Question < ActiveRecord::Base
  acts_as_list 

  belongs_to :question_category
  
  validates_presence_of :question_category_id, :question, :answer

  attr_accessible :question_id, :question, :answer
end

spree-faq/app/models/spree/question_category.rb
class Spree::QuestionCategory < ActiveRecord::Base
  acts_as_list 

  has_many :questions
  
  validates_uniqueness_of :name
  validates_presence_of :name

  accepts_nested_attributes_for :questions, :allow_destroy => true

  attr_accessible :name, :questions_attributes, :question, :answer
end

spree-faq/app/controllers/spree/admin/question_categories_controller.rb
module Spree
    module Admin
      class QuestionCategoriesController < ResourceController
        
        def new
          @question_category = @object
        end

        def edit
          @question_category = @object
        end    
      end
    end
  end

spree-faq/app/controllers/spree/faqs_controller.rb
class Spree::FaqsController < Spree::BaseController
  helper 'spree/products'
  include Spree::Core::ControllerHelpers::Order

  def index
    @categories = Spree::QuestionCategory.all(:include => :questions)
  end

  def default_title
    I18n.t 'frequently_asked_questions'
  end
end

spree-faq/app/views/spree/admin/question_categories/_question.html.erb
<div class="question" id="<%= dom_id f.object %>">
	<fieldset class="no-border-bottom">
	  <div class="field">
	    <%= f.label :question, t("question") %> <span class="required">*</span><br />
	    <%= f.text_field :question, :class => 'fullwidth title'  %>  
	  </div>
	  <div class="field">
	    <%= f.label :answer, t("answer") %> <span class="required">*</span><br />
	    <%= f.text_area :answer, :rows => 2, :class => 'fullwidth' %>  
	  </div>
	  <%= f.hidden_field :_destroy %>
	  <%= link_to_with_icon 'icon-trash', "remove", "#", :class => "remove" %>
  </fieldset>
</div>

spree-faq/app/views/spree/admin/question_categories/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:editing_category_questions) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:add_question), "#", :icon => 'icon-plus', :id => 'new_question_link' %>
    <%= button_link_to t(:back_to_categories), spree.admin_question_categories_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @question_category } %>

<%= form_for [:admin, @question_category] do |f| %>
  <%= javascript_tag do %>
     var new_question_html = '<%= generate_template(f, :questions) %>';
  <% end %>
  <div class="field">
    <%= f.field_container :name do %>
      <%= f.label :name, t("category_name") %> <span class="required">*</span><br />
      <%= f.text_field :name, :class => 'fullwidth title'  %>  
      <%= f.error_message_on :name %>
    <% end %>
  </div>
  <div id="questions" style="margin-bottom: 20px">
    <h3>Questions</h3>
      <%= f.fields_for :questions do |question_form| %>
        <%= render :partial => 'question', :locals => {:f => question_form } %>
      <% end %>
  </div>
  <div class="form-buttons filter-actions actions" data-hook="buttons">
    <%= button t(:update), 'icon-refresh' %>
    <span class="or"><%= t(:or) %></span>
    <%= link_to_with_icon 'icon-remove', t(:cancel), admin_question_categories_url, :class => 'button' %>
  </div>                                     
<% end %>

spree-faq/app/views/spree/admin/question_categories/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:question_categories) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_question_category_link">
        <%= button_link_to t(:new_question_category), new_admin_question_category_url, 
        {:remote => true, :icon => 'icon-plus', 'data-update' =>'new_question_category', :id => 'new_question_category_link' } %>
  </li>
<% end %>

<div id="new_question_category"></div>

<table class="index" id='listing_faq'>
  <colgroup>
    <col style="width: 40%">
    <col style="width: 40%">
    <col style="width: 20%">
  </colgroup>
  <thead>
    <tr data-hook="admin_faq_category_index_headers">
      <th><%= t(:category) %></td>
      <th><%= t(:questions) %></td>
      <th data-hook="admin_faq_category_index_header_actions" class="actions"></th>
    </tr>
  <thead>
  <tbody>
    <% @question_categories.each do |category| %>
      <tr id="<%= spree_dom_id category %>" data-hook="admin_faq_category_index_rows" class="<%= cycle('odd', 'even') %>" > 
        <td><%= h category.name %></td>
        <td><%= category.questions.count %></td>
        <td data-hook="admin_faq_category_index_row_actions" class="actions">
          <%= link_to_edit category, :no_text => true %>
          <%= link_to_delete category, :no_text => true  %>
        </td>
      </tr>
    <% end %> 
  </tbody>
</table>

spree-faq/app/views/spree/admin/question_categories/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:new_question_categories) %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @question_category} %>
<%= form_for [:admin, @question_category] do |f| %>
  <fieldset class="no-border-top">
      <%= f.field_container :name do %>
          <%= f.label :name, t("name") %> <span class="required">*</span><br />
          <%= f.text_field :name, :class => 'fullwidth title'  %>  
          <%= f.error_message_on :name %>
      <% end %>
      <div data-hook="buttons" class="filter-actions actions">
      	<%= button t(:create), 'icon-ok' %>
    	</div>
  </fieldset>
<% end %>

spree-faq/app/views/spree/admin/question_categories/new.js.erb
$("#new_question_category").html('<%= escape_javascript(render :template => "spree/admin/question_categories/new", :formats => [:html], :handlers => [:erb]) %>');
$("#new_question_category_link").parent().hide();

spree-faq/app/views/spree/faqs/index.html.erb
<h1><%= t('frequently_asked_questions') %></h1>

<div id="faqs">
  <% @categories = Spree::QuestionCategory.all(:include => :questions) %>
  <% @categories.each do |category| %>
    <div id="<%= dom_id category -%>" class="category">
      <h2><%= h category.name %></h2>
      <ul class="answers">
        <% category.questions.each do |question| %>
          <li>
            <a class="question" id="<%= dom_id question -%>" href="#<%= "answer_#{question.id}" %>">
              <%= raw(question.question) -%>
            </a>
            <div class="answer" id="<%= "answer_#{question.id}"-%>">
              <%= raw(question.answer) %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>   

<% content_for :sidebar do %>
    <% if "products" == @current_controller && @taxon %>
      <%= render "spree/shared/filters" %>
    <% else %>
      <%= render "spree/shared/taxonomies" %>
    <% end %>
<% end %>