spree_essentials/config/routes.rb
#Rails.application
Spree::Core::Engine.routes.draw do
  namespace :admin do
    post "/markdown/preview" => "markdown#preview", :as => :markdown_preview
    resources :uploads
  end
end

spree_essentials/app/models/spree/asset_decorator.rb
::Spree::Asset.class_eval do
  
  def has_alt?
    alt.present?
  end

end

spree_essentials/app/models/spree/upload.rb
class Spree::Upload < ::Spree::Asset
  
  attr_accessible :attachment, :alt
  
  default_scope where(:type => "Upload") if table_exists?
  
  validate :no_attachement_errors
  
  has_attached_file :attachment,
    :styles        => Proc.new{ |clip| clip.instance.attachment_sizes },
    :default_style => :medium,
    :url           => "/spree/uploads/:id/:style/:basename.:extension",
    :path          => ":rails_root/public/spree/uploads/:id/:style/:basename.:extension"
  
  def image_content?
    attachment_content_type.match(/\/(jpeg|png|gif|tiff|x-photoshop)/)
  end
     
  def attachment_sizes
    if image_content?
      { :mini => '48x48>', :small => '150x150>', :medium => '420x300>', :large => '800x500>' }
    else
      {}
    end
  end
  
  def no_attachement_errors
    if attachment_file_name.blank? || !attachment.errors.empty?
      # uncomment this to get rid of the less-than-useful interrim messages
      errors.clear
      errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
      false
    end
  end

end

spree_essentials/app/controllers/spree/admin/markdown_controller.rb
class Spree::Admin::MarkdownController < Spree::Admin::BaseController

  def preview
    render :text => RDiscount.new(params[:data].to_s).to_html
  end 

end

spree_essentials/app/controllers/spree/admin/uploads_controller.rb
class Spree::Admin::UploadsController < Spree::Admin::ResourceController
  
	def index
	  render :template => "spree/admin/uploads/#{request.xhr? ? 'picker' : 'index'}", :layout => !request.xhr?
  end
  
  private
  
    def collection
      params[:q] ||= {}
      params[:q][:sort] ||= "created_at.desc"
      @search = Spree::Upload.search(params[:q])
      @collection = @search.result.page(params[:page]).per(Spree::Config[:orders_per_page])
    end

end

spree_essentials/app/helpers/spree/admin/spree_essentials_helper.rb
module Spree::Admin::SpreeEssentialsHelper
  
  def inside_contents_tab?
    return false
  end
  
  def contents_tab
    content_tag :li do
      link_to I18n.t('spree.admin.shared.contents_tab.content'), extension_routes.first
    end
  end
  
  def markdown_helper
    content_tag('em', :class => 'small markdown-helper') do
      [ 
        t('essentials.parsed_with'),
        link_to("Markdown", "http://daringfireball.net/projects/markdown/basics", :onclick => 'window.open(this.href); return false')
      ].join(" ").html_safe
    end
  end

private
  
  def extension_routes
    @extension_routes ||= SpreeEssentials.essentials.map { |key, cls|
      route = cls.tab[:route] || "admin_#{key}"
      send("#{route}_path") rescue "##{key}"      
    }.push(spree.admin_uploads_path)    
  end
  
end

spree_essentials/app/views/spree/admin/shared/_contents_sub_menu.html.erb
<% if inside_contents_tab? %>
  <% content_for :sub_menu do %>
    <ul id="sub_nav" data-hook="essentials_sub_nav">
      <% SpreeEssentials.essentials.each_pair do |name, cls| %>
        <%= tab *cls.sub_tab if defined?(cls.sub_tab) %>
      <% end %>
      <%= tab :uploads, :label => t('spree.admin.subnav.uploads') %>
    </ul>
  <% end %>
<% end %>

spree_essentials/app/views/spree/admin/shared/_contents_tab.html.erb
<%= contents_tab %>

spree_essentials/app/views/spree/admin/uploads/_form.html.erb
<p>
  <%= form.label :attachment %>:<br/>
  <%= form.file_field :attachment %>
</p>
<p>
  <%= form.label :alt, t('description') %>:<br/>
  <%= form.text_field :alt, :class => 'text' %>
</p>

spree_essentials/app/views/spree/admin/uploads/edit.html.erb
<h1><%= t('.edit_upload') %></h1>

<% if @upload.try(:errors).present? %>
  <%= render 'shared/error_messages', :target => @upload %>
<% end %>

<%= form_for([:admin, @upload], :html => { :multipart => true }) do |f| %>
    <p>
      <% if @upload.image_content? %>
        <b><%= t('.preview') %>:</b><br/>
        <%= link_to image_tag(@upload.attachment.url(:small)), @upload.attachment.url(:original) %>
      <% else %>
        <b><%= t('.link') %>:</b><br/>
        <%= link_to @upload.attachment_file_name, @upload.attachment.url %>
      <% end %>
    </p>
    <%= render "form", :form => f %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    or <%= link_to t("cancel"), admin_uploads_url, :id => "cancel_link" %>
  </p>
<% end %>

spree_essentials/app/views/spree/admin/uploads/index.html.erb
<h1><%= t('.listing_uploads') %></h1>

<table class="index">
	<tr>
	  <th><%= t("thumbnail") %></th>
	  <th><%= sort_link @search, :attachment_file_name, t("upload.file_name") %></th>
	  <th><%= sort_link @search, :description, t("description") %></th>
	  <th><%= sort_link @search, :attachment_file_size, t("upload.size") %></th>
	  <th><%= t("action") %></th>
	</tr>
 
  <% @uploads.each do |upload| %>
    <tr id="<%= dom_id(upload) %>">
      <td class="thumbnail">
        <% if upload.image_content? %>
          <%= link_to image_tag(upload.attachment.url(:mini)), upload.attachment.url(:large) %>
        <% end %>
      </td>
      <td><%= link_to upload.attachment_file_name, upload.attachment.url(:original) %></td>
      <td><%= upload.alt %></td>
      <td><%= upload.attachment_file_size.to_i / 1024 %> kb</td>
      <td class="actions">
        <%= link_to_with_icon('edit', t("edit"), edit_admin_upload_url(upload)) %>
        &nbsp;
        <%= link_to_delete upload, {:url => admin_upload_url(upload) }%>
      </td>
    </tr>
  <% end %>
 
</table>

<%= paginate @uploads %>


<% content_for :sidebar do %>

<div class="box">
  <h3><%= t(:search) %></h3>
  <%= search_form_for [ :admin, @search ] do |f| %>
    <p>
      <%= f.label :alt_cont, t("description") %><br />
      <%= f.text_field :alt_cont, :size => 25 %>
    </p>
    <p><%= button t("search") %></p>
  <% end %>
</div>
<% end %>

<div id="images"></div>
<br/>
<p>
  <%= link_to icon('add') + ' ' + t(".new_upload"), new_admin_upload_url, :id => "new_image_link" %>
</p>

<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){  
      
      jQuery('#new_image_link').click(function(event) { 
        event.preventDefault();
        jQuery(this).hide();
        jQuery.ajax({type: 'GET', url: this.href, data: ({authenticity_token: AUTH_TOKEN}), success: function(r){ jQuery('#images').html(r);} });
      });
      
    });
  </script>
<% end %>

spree_essentials/app/views/spree/admin/uploads/new.html.erb
<h3><%= t('.new_upload') %></h3>

<% if @upload.try(:errors).present? %>
  <%= render 'shared/error_messages', :target => @upload %>
<% end %>

<%= form_for([:admin, @upload], :html => { :multipart => true }) do |form| %>
  <table class="basic-table">
    <%= render "form", :form => form %>
  </table>
  <p class="form-buttons">
    <%= button t("create") %>
    or <%= link_to t("cancel"), "#", :id => "cancel_link" %>
  </p>
<% end %>

<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_image_link').show();
    jQuery('#images').html('');
  }); 
</script>

spree_essentials/app/views/spree/admin/uploads/picker.html.erb
<ul class="picker">
<% @uploads.each do |upload| %>
  <li>
    <% if upload.image_content? %>
      <%= link_to image_tag(upload.attachment.url(:mini)), upload.attachment.url(:original), :class => 'option image' %>
    <% else %>
      <%= link_to upload.attachment_file_name, upload.attachment.url(:original), :class => 'option file' %>
    <% end %>
  </li>
<% end %>
</ul>